### ISSUE TITLE
Identificación

### ISSUE THREAD

**Issue by pedroprieto** [JorgeJGR/JJGR#1]
Buenas, @JorgeJGR . He recibido tu invitación al repositorio. ¿Eres un alumno? ¿Podrías identificarte?

Gracias y un saludo!

**Comment by pedroprieto** [comment]
Necesito saber también qué práctica estás haciendo. Gracias!

**Comment by JorgeJGR** [comment]
Hola, soy Jorge.
Soy alumno del IES Doctor Balmis. Nos han pasado videos tuyos de cómo hacer
un Fork con GitHub.
En un ejercicio de entrega sobre GitHub teníamos que hacer un Fork y me
fijado en cómo lo has hecho en tú video.
Espero no haberte molestado y haberlo hecho bien.
Un saludo, Jorge Juan Guijarro Tabasco.
P.D. Mi hijo está matriculado en el IES Mare Nostrum, también en
semipresencial de DAM, eres profesor de allí?

**Comment by pedroprieto** [comment]
Buenas,

Encantado, Jorge :relaxed: 

Todo aclarado pues. Lo único, seguramente tendrías que hacer un fork de un repositorio de tu profesor :wink: No pasa nada, no te preocupes. Es que no te tenía localizado en mis clases.

Sí, soy profesor del Mare Nostrum. Doy semipresencial en 2º de DAM. Si cursa Desarrollo de Interfaces seguramente le daré clase. ¿Quién es?

Un saludo!!

**Comment by JorgeJGR** [comment]
Se llama Jorge Guijarro Fuentes pero es de primero DAM.

**Comment by pedroprieto** [comment]
Ah, entonces no le doy clase. El año que viene seguramente :wink: 

Un saludo y ánimo con el curso!!

**Comment by JorgeJGR** [comment]
Espero ver tus vídeos y ponerme al día. Lo veo muy interesante pero me
aclaro mejor por consola. Me imagino que será practicando cuando lo vea más
claro!!

Yo fui alumno del IES Mare Nostrum en informática cuando aún era F.P. allá
por los finales de los años 90. Cuánto ha avanzado la informática!! Menos
mal que me queda la base.

Un saludo, Jorge J.

**Comment by pedroprieto** [comment]
Sí que ha avanzado, sí. Ánimo pues!
